### ISSUE TITLE
[Request] requirements.txt

### ISSUE THREAD

**Issue by LukeAI** [rgeirhos/Stylized-ImageNet#1]
Hi! Thanks a bunch for this great repo.
Just to make things easy for us lazy users, would it be possible to provide a requirements.txt so that I don't have to keep running the script again and again just to find out what libraries I need? Alternatively, give me a one-liner for the docker? A link to a docker image doesn't tell me how I am supposed to specify the paths and run it properly.

**Comment by rgeirhos** [comment]
Hi @LukeAI good suggestion; I have added a requirements.txt generated with pipreqs (commit c23a840416b5fcb88ed7784432fd36bc8c7701df). Does this address your request?
