### ISSUE TITLE
Fraction of 'shape' decisions and Fraction of 'texture' decisions

### ISSUE THREAD

**Issue by ruthvik92** [rgeirhos/Stylized-ImageNet#10]
Hi Robert,
This is more of a question than an issue, in Figure 4: How did you decide "Fraction of 'shape' decisions" and "Fraction of 'texture' decisions". In case of humans you can simply ask them if they went with the shape or the texture but in the case of the CNNs how did you calculate the percentage?

**Comment by rgeirhos** [comment]
Solved by https://github.com/rgeirhos/texture-vs-shape/issues/17
Generally speaking, I would recommend avoiding to open multiple related issues across different repositories.
