### ISSUE TITLE
About checkpoint file

### ISSUE THREAD

**Issue by wangtingwei1993** [rgeirhos/Stylized-ImageNet#11]
Hi, I just want to double check that you use the pre-trained vgg19 and decoder networks from AdaIN paper to stylize the ImageNet dataset, right? You did not re-train the decoder based on your dataset. 

Please point out if I make any mistake.

Thanks!

**Comment by rgeirhos** [comment]
Yes. I used the vanilla setup from https://github.com/naoto0804/pytorch-AdaIN without any re-training. BTW, perhaps you may also take a look at https://github.com/bethgelab/stylize-datasets which may be a bit easier to use.
