### ISSUE TITLE
Conflicting torch / numpy versions

### ISSUE THREAD

**Issue by arielnlee** [rgeirhos/Stylized-ImageNet#20]
Hello! I'd really like to use this library but pytorch 0.4.1 is only supported through python 3.7 and numpy 1.22.0 is supported starting with python 3.8.  Using an older version of numpy causes an import error. Any suggestions? I have 1 nvidia GPU and I'm using conda to set up my env. Thanks!

Also, when I try the docker route I get the error: Running as root is not recommended. Use --allow-root to bypass

**Comment by arielnlee** [comment]
I fixed this by adding jupyter notebook --allow-root at the end of the docker run statement. Thanks!

**Comment by rgeirhos** [comment]
Hey there, glad to hear you were able to resolve the issue!

**Comment by Alxmrphi** [comment]
I'm quite new to Docker and I'm running into the same issue. Can I ask exactly how you added the `--allow-root` command to the end of the docker run statement? 

If I run it with just the command:

```
docker run -t bethgelab/deeplearning:cuda10.0-cudnn7-12_2019
>> [I 15:17:10.264 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
>> [I 15:17:10.304 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
>> [I 15:17:12.766 NotebookApp] jupyter_tensorboard extension loaded.
>> [I 15:17:13.097 NotebookApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
>> [I 15:17:13.097 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
>> [C 15:17:13.386 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
```

I am looking at the details in the Docker GUI and I believe I need to add this in `
CMD ["/usr/local/bin/run_jupyter.sh"]`, right? Any help appreciated.
