### ISSUE TITLE
recommendations for training

### ISSUE THREAD

**Issue by LukeAI** [rgeirhos/Stylized-ImageNet#4]
I'm currently training a variation on darknet19 on IN+SIN at 224 x 224
My aim is to get the highest AP object detector that I can based on transfering from these weights. I understand that in the original paper, best results were achieved by training on IN + SIN and then finetuning on IN only. At what point would you suggest doing the finetuning? Is it after the AP for IN+SIN has started to level off or whilst it is still rising?
I also plan to finetune at a greater resolution - maybe 448 x 448 - do you think I should do this after finetuning on IN only at 224 x 224 ?

**Comment by rgeirhos** [comment]
Concerning your first question, I would probably start the fine-tuning after the AP for IN+SIN is no longer increasing (that would be my best guess). Unfortunately I don't have any insights with respect to training at different resolutions.

Good luck with your experiments!
