### ISSUE TITLE
imagenet root problem.

### ISSUE THREAD

**Issue by iminfine** [rgeirhos/Stylized-ImageNet#6]
I set the IMAGENET_PATH to where I store the datasets, but I got this problem when I run the code:

Traceback (most recent call last):
  File "preprocess_imagenet.py", line 211, in <module>
    main()
  File "preprocess_imagenet.py", line 111, in main
    sampler = None)
  File "preprocess_imagenet.py", line 93, in __init__
    target_transform = target_transform)
  File "/users/k1898460/.conda/envs/SIN/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 209, in __init__
    target_transform=target_transform)
  File "/users/k1898460/.conda/envs/SIN/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 87, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: /mnt/lustre/users/k1898460/ILSVRC/Data/CLS-LOC/val
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,webp

The files in val folder are like this:
ILSVRC2012_val_00024986.JPEG  ILSVRC2012_val_00049986.JPEG
ILSVRC2012_val_00024987.JPEG  ILSVRC2012_val_00049987.JPEG
ILSVRC2012_val_00024988.JPEG  ILSVRC2012_val_00049988.JPEG
ILSVRC2012_val_00024989.JPEG  ILSVRC2012_val_00049989.JPEG
ILSVRC2012_val_00024990.JPEG  ILSVRC2012_val_00049990.JPEG
ILSVRC2012_val_00024991.JPEG  ILSVRC2012_val_00049991.JPEG
ILSVRC2012_val_00024992.JPEG  ILSVRC2012_val_00049992.JPEG
ILSVRC2012_val_00024993.JPEG  ILSVRC2012_val_00049993.JPEG
ILSVRC2012_val_00024994.JPEG  ILSVRC2012_val_00049994.JPEG
ILSVRC2012_val_00024995.JPEG  ILSVRC2012_val_00049995.JPEG
ILSVRC2012_val_00024996.JPEG  ILSVRC2012_val_00049996.JPEG
ILSVRC2012_val_00024997.JPEG  ILSVRC2012_val_00049997.JPEG
ILSVRC2012_val_00024998.JPEG  ILSVRC2012_val_00049998.JPEG
ILSVRC2012_val_00024999.JPEG  ILSVRC2012_val_00049999.JPEG
ILSVRC2012_val_00025000.JPEG  ILSVRC2012_val_00050000.JPEG

Is something wrong?

**Comment by rgeirhos** [comment]
Judging from the error message, it looks like you're storing the files directly in val/, whereas they're expected to be in *sub*folders of val/. The subdirectory structure should follow standard the ImageNet structure where every class is in its own folder.

**Comment by iminfine** [comment]
> Judging from the error message, it looks like you're storing the files directly in val/, whereas they're expected to be in _sub_folders of val/. The subdirectory structure should follow standard the ImageNet structure where every class is in its own folder.

Thanks, I created subfolders by this script: https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
The code works well right now.
