### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by DachengLi1** [rgeirhos/Stylized-ImageNet#8]
Is it possible to create stylized VOC? If so could you tell me how to do this? Thanks!

**Comment by rgeirhos** [comment]
It is indeed possible to create stylized VOC (or stylize any other image dataset, for that matter). We have published results for this here: https://arxiv.org/abs/1907.07484 and the corresponding code & benchmark here: https://github.com/bethgelab/robust-detection-benchmark. Hope it helps!

**Comment by DachengLi1** [comment]
Hi, Thanks for your help and awesome paper. I am concerned to reproduce the result that you showed in this paper that using stylized images can improve the original detection map, not the corrupted map. It seems like the other paper is concerning the robustness of detectors in corrupted scenes and using those styles cannot improve the original map. Is it using the texture provided in this github and use it to create stylized VOC that improves the original map? (I assume I may use some codes from the other github). Thank you!
