### ISSUE TITLE
Kaggle's painter-by-numbers dataset is not found

### ISSUE THREAD

**Issue by anindyasarkarIITH** [rgeirhos/Stylized-ImageNet#9]
I tried to download Kaggle's painter-by-numbers dataset from the link mentioned in README. But it is not there. Can you please provide modified link for downloading Kaggle's painter-by-numbers dataset?? Thanks

**Comment by rgeirhos** [comment]
I'm not entirely sure I understand.
The link from the README (https://www.kaggle.com/c/painter-by-numbers/data) still works.
You need to scroll down to the "Data (64GB)" section and if you hover over the file (e.g. train.zip) you'll see a download option like this one here:

![Screenshot from 2020-02-06 16-50-26](https://user-images.githubusercontent.com/23079422/73953548-dde7b900-4900-11ea-85ba-39af5fe56543.png)

If you don't see the download option you'll need to log in first (or create a Kaggle account if you don't have one).

**Comment by anindyasarkarIITH** [comment]
Thanks for your reply. Actually, I wanted to download in remote server
through "wget" command, which is not working for this dataset download
link. Though, I can download the zip file in local machine and they copy it
to remote server.
